spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/ecommerce
    password: root
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/   
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
server:
  port: 8081

auth-service:
 messages:
  userreg: User Created
  usererr: User Creation Failed
  loginsuccess: Login success
  loginerr: Login failed
